import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { useServerFn } from "@tanstack/react-start";
import { ShieldCheck } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { z } from "zod";
import logo from "@/assets/gbb-logo.png.asset.json";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { supabase } from "@/integrations/supabase/client";
import { getAdminSession } from "@/lib/admin.functions";

const schema=z.object({email:z.string().trim().email("Enter a valid email"),password:z.string().min(8,"Password must be at least 8 characters")});
export const Route=createFileRoute("/admin/login")({validateSearch:(s:Record<string,unknown>)=>({reason:typeof s.reason==="string"?s.reason:undefined}),head:()=>({meta:[{title:"Admin Sign In | GrowthBridge Bank"},{name:"description",content:"Secure staff access for GrowthBridge Bank operations."},{property:"og:title",content:"Admin Sign In | GrowthBridge Bank"},{property:"og:description",content:"Secure staff access for GrowthBridge Bank operations."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary"}]}),component:AdminLogin});
function AdminLogin(){const [busy,setBusy]=useState(false);const [errors,setErrors]=useState<Record<string,string>>({});const navigate=useNavigate();const search=Route.useSearch();const verify=useServerFn(getAdminSession);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const parsed=schema.safeParse({email:f.get("email"),password:f.get("password")});if(!parsed.success){const next:Record<string,string>={};for(const i of parsed.error.issues)next[String(i.path[0])]=i.message;setErrors(next);return;}setBusy(true);setErrors({});const {error}=await supabase.auth.signInWithPassword(parsed.data);if(error){setBusy(false);toast.error("Sign-in unsuccessful",{description:"Check your credentials and try again."});return;}try{await verify();toast.success("Admin access confirmed");await navigate({to:"/admin/dashboard",replace:true});}catch{await supabase.auth.signOut();setBusy(false);toast.error("Access not authorized",{description:"This account does not have staff access."});}}
 return <main className="grid min-h-screen place-items-center bg-gradient-navy px-4 py-10"><div className="w-full max-w-md rounded-lg border border-primary-foreground/15 bg-card p-6 shadow-elevated sm:p-8"><div className="text-center"><img src={logo.url} alt="GrowthBridge Bank" className="mx-auto size-16 rounded-full object-cover"/><p className="mt-4 text-xs font-semibold text-gold">GBB ADMIN PORTAL</p><h1 className="mt-2 font-display text-2xl font-semibold text-navy">Authorized staff sign in</h1><p className="mt-2 text-sm text-muted-foreground">Use your existing GrowthBridge staff account.</p></div>{search.reason&&<div className="mt-5 rounded-md border border-destructive/20 bg-destructive/5 p-3 text-sm text-destructive">Your account is not authorized for this area.</div>}<form onSubmit={submit} className="mt-6 space-y-4"><div className="space-y-2"><Label htmlFor="admin-email">Email</Label><Input id="admin-email" name="email" type="email" autoComplete="email" aria-invalid={!!errors.email}/>{errors.email&&<p className="text-xs text-destructive">{errors.email}</p>}</div><div className="space-y-2"><Label htmlFor="admin-password">Password</Label><Input id="admin-password" name="password" type="password" autoComplete="current-password" aria-invalid={!!errors.password}/>{errors.password&&<p className="text-xs text-destructive">{errors.password}</p>}</div><Button className="w-full" disabled={busy}><ShieldCheck className="size-4"/>{busy?"Verifying access…":"Sign in securely"}</Button></form><div className="mt-5 flex justify-between text-xs"><Link to="/forgot-password" className="text-muted-foreground hover:text-foreground">Forgot password?</Link><Link to="/" className="text-muted-foreground hover:text-foreground">Return to GBB</Link></div></div></main>;
}
