import { useQuery } from "@tanstack/react-query";
import { createFileRoute, Link } from "@tanstack/react-router";
import { useServerFn } from "@tanstack/react-start";
import { BanknoteArrowDown, BanknoteArrowUp, FileCheck2, HandCoins, Landmark, Send, Users } from "lucide-react";
import { AdminHeader, AdminPanel, DateTime, Money, PageError, PageLoading, StatusBadge } from "@/components/admin/AdminUI";
import { Table,TableBody,TableCell,TableHead,TableHeader,TableRow } from "@/components/ui/table";
import { getAdminOverview } from "@/lib/admin.functions";
export const Route=createFileRoute("/admin/dashboard")({head:()=>({meta:[{title:"Admin Dashboard | GBB"},{name:"description",content:"GrowthBridge Bank operations dashboard."},{property:"og:title",content:"Admin Dashboard | GBB"},{property:"og:description",content:"GrowthBridge Bank operations dashboard."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary"}]}),component:Dashboard});
function Dashboard(){const fn=useServerFn(getAdminOverview);const q=useQuery({queryKey:["admin-overview"],queryFn:()=>fn()});if(q.isLoading)return <PageLoading/>;if(q.isError||!q.data)return <PageError retry={()=>void q.refetch()}/>;const s=q.data.stats;const cards=[[/admin\/users/,"Customers",s.customers,Users],[/admin\/kyc/,"Pending KYC",s.pendingKyc,FileCheck2],[/admin\/deposits/,"Pending deposits",s.pendingDeposits,BanknoteArrowDown],[/admin\/withdrawals/,"Pending withdrawals",s.pendingWithdrawals,BanknoteArrowUp],[/admin\/transfers/,"Pending transfers",s.pendingTransfers,Send],[/admin\/loans/,"Pending loans",s.pendingLoans,HandCoins]] as const;return <><AdminHeader title="Dashboard" description="Live operational activity across GrowthBridge Bank."/><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{cards.map(([rx,label,value,Icon])=>{const to=rx.source.replaceAll("\\/","/").slice(0,-1);return <Link key={label} to={to} className="rounded-lg border bg-card p-5 shadow-sm transition hover:border-primary/30"><div className="flex items-center justify-between"><span className="grid size-10 place-items-center rounded-md bg-emerald-soft text-emerald-deep"><Icon className="size-5"/></span><span className="font-display text-2xl font-semibold text-navy">{value}</span></div><p className="mt-4 text-sm font-medium">{label}</p></Link>})}</div><div className="mt-6 grid gap-6 xl:grid-cols-[1.4fr_1fr]"><AdminPanel><div className="border-b p-4"><h2 className="font-display font-semibold text-navy">Recent transactions</h2></div><Table><TableHeader><TableRow><TableHead>Customer</TableHead><TableHead>Description</TableHead><TableHead>Amount</TableHead><TableHead>Status</TableHead></TableRow></TableHeader><TableBody>{q.data.recentTxns.map((r:any)=><TableRow key={r.id}><TableCell>{r.customer}</TableCell><TableCell><p>{r.description||r.type}</p><p className="text-xs text-muted-foreground"><DateTime value={r.created_at}/></p></TableCell><TableCell><Money amount={r.amount} currency={r.currency}/></TableCell><TableCell><StatusBadge status={r.status}/></TableCell></TableRow>)}</TableBody></Table></AdminPanel><AdminPanel><div className="border-b p-4"><h2 className="font-display font-semibold text-navy">Recent admin activity</h2></div><div className="divide-y">{q.data.recentActions.map((r:any)=><div key={r.id} className="p-4"><div className="flex items-start justify-between gap-3"><p className="text-sm font-medium capitalize">{String(r.action||"action").replace(/_/g," ")}</p><Landmark className="size-4 shrink-0 text-muted-foreground"/></div><p className="mt-1 text-xs text-muted-foreground">{r.actor_email||"Authorized staff"} · <DateTime value={r.created_at}/></p></div>)}</div></AdminPanel></div></>}
