/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BusinessRouteImport } from './routes/business'
import { Route as CardsRouteImport } from './routes/cards'
import { Route as CardsOverviewRouteImport } from './routes/cards-overview'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as CheckingRouteImport } from './routes/checking'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as HelpRouteImport } from './routes/help'
import { Route as InvestingRouteImport } from './routes/investing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MeRouteImport } from './routes/me'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as PersonalRouteImport } from './routes/personal'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RewardsOverviewRouteImport } from './routes/rewards-overview'
import { Route as SavingsRouteImport } from './routes/savings'
import { Route as SecurityOverviewRouteImport } from './routes/security-overview'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminDepositsRouteImport } from './routes/admin.deposits'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminWithdrawalsRouteImport } from './routes/admin.withdrawals'
import { Route as LegalDisclosuresRouteImport } from './routes/legal/disclosures'
import { Route as LegalElectronicCommunicationsRouteImport } from './routes/legal/electronic-communications'
import { Route as LegalInvestmentRiskRouteImport } from './routes/legal/investment-risk'
import { Route as LegalPrivacyRouteImport } from './routes/legal/privacy'
import { Route as LegalRewardsTermsRouteImport } from './routes/legal/rewards-terms'
import { Route as LegalTermsRouteImport } from './routes/legal/terms'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRoute = BusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsRoute = CardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsOverviewRoute = CardsOverviewRouteImport.update({
  id: '/cards-overview',
  path: '/cards-overview',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckingRoute = CheckingRouteImport.update({
  id: '/checking',
  path: '/checking',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestingRoute = InvestingRouteImport.update({
  id: '/investing',
  path: '/investing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalRoute = PersonalRouteImport.update({
  id: '/personal',
  path: '/personal',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsOverviewRoute = RewardsOverviewRouteImport.update({
  id: '/rewards-overview',
  path: '/rewards-overview',
  getParentRoute: () => rootRouteImport,
} as any)
const SavingsRoute = SavingsRouteImport.update({
  id: '/savings',
  path: '/savings',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityOverviewRoute = SecurityOverviewRouteImport.update({
  id: '/security-overview',
  path: '/security-overview',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDepositsRoute = AdminDepositsRouteImport.update({
  id: '/deposits',
  path: '/deposits',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWithdrawalsRoute = AdminWithdrawalsRouteImport.update({
  id: '/withdrawals',
  path: '/withdrawals',
  getParentRoute: () => AdminRoute,
} as any)
const LegalDisclosuresRoute = LegalDisclosuresRouteImport.update({
  id: '/legal/disclosures',
  path: '/legal/disclosures',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalElectronicCommunicationsRoute =
  LegalElectronicCommunicationsRouteImport.update({
    id: '/legal/electronic-communications',
    path: '/legal/electronic-communications',
    getParentRoute: () => rootRouteImport,
  } as any)
const LegalInvestmentRiskRoute = LegalInvestmentRiskRouteImport.update({
  id: '/legal/investment-risk',
  path: '/legal/investment-risk',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRewardsTermsRoute = LegalRewardsTermsRouteImport.update({
  id: '/legal/rewards-terms',
  path: '/legal/rewards-terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/business': typeof BusinessRoute
  '/cards': typeof CardsRoute
  '/cards-overview': typeof CardsOverviewRoute
  '/careers': typeof CareersRoute
  '/checking': typeof CheckingRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/finance': typeof FinanceRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/investing': typeof InvestingRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/payments': typeof PaymentsRoute
  '/personal': typeof PersonalRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rewards-overview': typeof RewardsOverviewRoute
  '/savings': typeof SavingsRoute
  '/security-overview': typeof SecurityOverviewRoute
  '/transactions': typeof TransactionsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/deposits': typeof AdminDepositsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/legal/disclosures': typeof LegalDisclosuresRoute
  '/legal/electronic-communications': typeof LegalElectronicCommunicationsRoute
  '/legal/investment-risk': typeof LegalInvestmentRiskRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/rewards-terms': typeof LegalRewardsTermsRoute
  '/legal/terms': typeof LegalTermsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/business': typeof BusinessRoute
  '/cards': typeof CardsRoute
  '/cards-overview': typeof CardsOverviewRoute
  '/careers': typeof CareersRoute
  '/checking': typeof CheckingRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/finance': typeof FinanceRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/investing': typeof InvestingRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/payments': typeof PaymentsRoute
  '/personal': typeof PersonalRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rewards-overview': typeof RewardsOverviewRoute
  '/savings': typeof SavingsRoute
  '/security-overview': typeof SecurityOverviewRoute
  '/transactions': typeof TransactionsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/deposits': typeof AdminDepositsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/legal/disclosures': typeof LegalDisclosuresRoute
  '/legal/electronic-communications': typeof LegalElectronicCommunicationsRoute
  '/legal/investment-risk': typeof LegalInvestmentRiskRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/rewards-terms': typeof LegalRewardsTermsRoute
  '/legal/terms': typeof LegalTermsRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/business': typeof BusinessRoute
  '/cards': typeof CardsRoute
  '/cards-overview': typeof CardsOverviewRoute
  '/careers': typeof CareersRoute
  '/checking': typeof CheckingRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/finance': typeof FinanceRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/investing': typeof InvestingRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/payments': typeof PaymentsRoute
  '/personal': typeof PersonalRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rewards-overview': typeof RewardsOverviewRoute
  '/savings': typeof SavingsRoute
  '/security-overview': typeof SecurityOverviewRoute
  '/transactions': typeof TransactionsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/deposits': typeof AdminDepositsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/legal/disclosures': typeof LegalDisclosuresRoute
  '/legal/electronic-communications': typeof LegalElectronicCommunicationsRoute
  '/legal/investment-risk': typeof LegalInvestmentRiskRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/rewards-terms': typeof LegalRewardsTermsRoute
  '/legal/terms': typeof LegalTermsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/business'
    | '/cards'
    | '/cards-overview'
    | '/careers'
    | '/checking'
    | '/contact'
    | '/dashboard'
    | '/finance'
    | '/forgot-password'
    | '/help'
    | '/investing'
    | '/login'
    | '/me'
    | '/payments'
    | '/personal'
    | '/register'
    | '/reset-password'
    | '/rewards-overview'
    | '/savings'
    | '/security-overview'
    | '/transactions'
    | '/admin/dashboard'
    | '/admin/deposits'
    | '/admin/login'
    | '/admin/users'
    | '/admin/withdrawals'
    | '/legal/disclosures'
    | '/legal/electronic-communications'
    | '/legal/investment-risk'
    | '/legal/privacy'
    | '/legal/rewards-terms'
    | '/legal/terms'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/business'
    | '/cards'
    | '/cards-overview'
    | '/careers'
    | '/checking'
    | '/contact'
    | '/dashboard'
    | '/finance'
    | '/forgot-password'
    | '/help'
    | '/investing'
    | '/login'
    | '/me'
    | '/payments'
    | '/personal'
    | '/register'
    | '/reset-password'
    | '/rewards-overview'
    | '/savings'
    | '/security-overview'
    | '/transactions'
    | '/admin/dashboard'
    | '/admin/deposits'
    | '/admin/login'
    | '/admin/users'
    | '/admin/withdrawals'
    | '/legal/disclosures'
    | '/legal/electronic-communications'
    | '/legal/investment-risk'
    | '/legal/privacy'
    | '/legal/rewards-terms'
    | '/legal/terms'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/business'
    | '/cards'
    | '/cards-overview'
    | '/careers'
    | '/checking'
    | '/contact'
    | '/dashboard'
    | '/finance'
    | '/forgot-password'
    | '/help'
    | '/investing'
    | '/login'
    | '/me'
    | '/payments'
    | '/personal'
    | '/register'
    | '/reset-password'
    | '/rewards-overview'
    | '/savings'
    | '/security-overview'
    | '/transactions'
    | '/admin/dashboard'
    | '/admin/deposits'
    | '/admin/login'
    | '/admin/users'
    | '/admin/withdrawals'
    | '/legal/disclosures'
    | '/legal/electronic-communications'
    | '/legal/investment-risk'
    | '/legal/privacy'
    | '/legal/rewards-terms'
    | '/legal/terms'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  BusinessRoute: typeof BusinessRoute
  CardsRoute: typeof CardsRoute
  CardsOverviewRoute: typeof CardsOverviewRoute
  CareersRoute: typeof CareersRoute
  CheckingRoute: typeof CheckingRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  FinanceRoute: typeof FinanceRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HelpRoute: typeof HelpRoute
  InvestingRoute: typeof InvestingRoute
  LoginRoute: typeof LoginRoute
  MeRoute: typeof MeRoute
  PaymentsRoute: typeof PaymentsRoute
  PersonalRoute: typeof PersonalRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RewardsOverviewRoute: typeof RewardsOverviewRoute
  SavingsRoute: typeof SavingsRoute
  SecurityOverviewRoute: typeof SecurityOverviewRoute
  TransactionsRoute: typeof TransactionsRoute
  LegalDisclosuresRoute: typeof LegalDisclosuresRoute
  LegalElectronicCommunicationsRoute: typeof LegalElectronicCommunicationsRoute
  LegalInvestmentRiskRoute: typeof LegalInvestmentRiskRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalRewardsTermsRoute: typeof LegalRewardsTermsRoute
  LegalTermsRoute: typeof LegalTermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards': {
      id: '/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof CardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards-overview': {
      id: '/cards-overview'
      path: '/cards-overview'
      fullPath: '/cards-overview'
      preLoaderRoute: typeof CardsOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checking': {
      id: '/checking'
      path: '/checking'
      fullPath: '/checking'
      preLoaderRoute: typeof CheckingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investing': {
      id: '/investing'
      path: '/investing'
      fullPath: '/investing'
      preLoaderRoute: typeof InvestingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personal': {
      id: '/personal'
      path: '/personal'
      fullPath: '/personal'
      preLoaderRoute: typeof PersonalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards-overview': {
      id: '/rewards-overview'
      path: '/rewards-overview'
      fullPath: '/rewards-overview'
      preLoaderRoute: typeof RewardsOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/savings': {
      id: '/savings'
      path: '/savings'
      fullPath: '/savings'
      preLoaderRoute: typeof SavingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security-overview': {
      id: '/security-overview'
      path: '/security-overview'
      fullPath: '/security-overview'
      preLoaderRoute: typeof SecurityOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/deposits': {
      id: '/admin/deposits'
      path: '/deposits'
      fullPath: '/admin/deposits'
      preLoaderRoute: typeof AdminDepositsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/withdrawals': {
      id: '/admin/withdrawals'
      path: '/withdrawals'
      fullPath: '/admin/withdrawals'
      preLoaderRoute: typeof AdminWithdrawalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/legal/disclosures': {
      id: '/legal/disclosures'
      path: '/legal/disclosures'
      fullPath: '/legal/disclosures'
      preLoaderRoute: typeof LegalDisclosuresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/electronic-communications': {
      id: '/legal/electronic-communications'
      path: '/legal/electronic-communications'
      fullPath: '/legal/electronic-communications'
      preLoaderRoute: typeof LegalElectronicCommunicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/investment-risk': {
      id: '/legal/investment-risk'
      path: '/legal/investment-risk'
      fullPath: '/legal/investment-risk'
      preLoaderRoute: typeof LegalInvestmentRiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/rewards-terms': {
      id: '/legal/rewards-terms'
      path: '/legal/rewards-terms'
      fullPath: '/legal/rewards-terms'
      preLoaderRoute: typeof LegalRewardsTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDepositsRoute: typeof AdminDepositsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWithdrawalsRoute: typeof AdminWithdrawalsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDepositsRoute: AdminDepositsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWithdrawalsRoute: AdminWithdrawalsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  BusinessRoute: BusinessRoute,
  CardsRoute: CardsRoute,
  CardsOverviewRoute: CardsOverviewRoute,
  CareersRoute: CareersRoute,
  CheckingRoute: CheckingRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  FinanceRoute: FinanceRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HelpRoute: HelpRoute,
  InvestingRoute: InvestingRoute,
  LoginRoute: LoginRoute,
  MeRoute: MeRoute,
  PaymentsRoute: PaymentsRoute,
  PersonalRoute: PersonalRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RewardsOverviewRoute: RewardsOverviewRoute,
  SavingsRoute: SavingsRoute,
  SecurityOverviewRoute: SecurityOverviewRoute,
  TransactionsRoute: TransactionsRoute,
  LegalDisclosuresRoute: LegalDisclosuresRoute,
  LegalElectronicCommunicationsRoute: LegalElectronicCommunicationsRoute,
  LegalInvestmentRiskRoute: LegalInvestmentRiskRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalRewardsTermsRoute: LegalRewardsTermsRoute,
  LegalTermsRoute: LegalTermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
